version: '3'

services:
  app:
    build: .
    environment:
      MONOBANK_TOKEN: ${MONOBANK_TOKEN}
      MONGO_HOST: db
      MONGO_PORT: 27017
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
      MONGO_DB: family-balance
      TG_BOT_TOKEN: ${TG_BOT_TOKEN}
      TG_CHAT: ${TG_CHAT}

  db:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - ./db:/data/db
