version: '3'

services:
  app:
    #build: .
    image: node:14-alpine
    volumes:
      - .:/app
    environment:
      MONOBANK_TOKEN: ${MONOBANK_TOKEN}
      MONGO_HOST: db
      MONGO_PORT: 27017
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
      MONGO_DB: family-balance
    command:
      - node
      - /app/src/app.js

  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - ./db:/data/db
